name: "Build and deploy to GitHub Pages"
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Build Vue app
        env:
          # Set the repository variable BAZAAR_APP_ID to your app ID from cloud.bzr.dev/developers.
          VITE_APP_ID: ${{ vars.BAZAAR_APP_ID }}
          VITE_BASE: /${{ github.event.repository.name }}/
        run: |
          pnpm install --frozen-lockfile
          pnpm test
          pnpm run build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
